/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Authentication1 from 'src/components/Authentication1/Authentication1';
import SideBarLogin from 'src/components/SideBarLogin/SideBarLogin';
import { MacBookPro161Props } from 'src/types';

const MacBookPro1611: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1080px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Authentication11: any = styled(Authentication1)(({ theme }: any) => ({
  width: `530px`,
  height: `840px`,
  position: `absolute`,
  left: `695px`,
  top: `120px`,
}));

const SideBarLogin1: any = styled(SideBarLogin)(({ theme }: any) => ({
  width: `125px`,
  height: `1080px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

function MacBookPro161(props: MacBookPro161Props): JSX.Element {
  return (
    <MacBookPro1611 className={props.className}>
      <Authentication11 />
      <SideBarLogin1 />
    </MacBookPro1611>
  );
}

export default MacBookPro161;
