/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import User11Image from 'src/assets/images/UserControlSettings_user__1__1.png';
import Setting1Image from 'src/assets/images/UserControlSettings_setting_1.png';
import { styled } from '@mui/material/styles';
import { UserControlSettingsProps } from 'src/types';

const UserControlSettings1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `45px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const User11: any = styled('img')({
  height: `35px`,
  width: `35.6px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `6px`,
});

const Setting1: any = styled('img')({
  height: `35px`,
  width: `35px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `64px`,
  top: `6px`,
});

function UserControlSettings(props: UserControlSettingsProps): JSX.Element {
  return (
    <UserControlSettings1 className={props.className}>
      <User11 src={User11Image} loading="lazy" alt={'user (1) 1'} />
      <Setting1 src={Setting1Image} loading="lazy" alt={'setting 1'} />
    </UserControlSettings1>
  );
}

export default UserControlSettings;
