/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Setup1Image from 'src/assets/images/DashboardCards_setup_1.png';
import Setup2Image from 'src/assets/images/DashboardCards_setup_2.png';
import Setup3Image from 'src/assets/images/DashboardCards_setup_3.png';
import Setup4Image from 'src/assets/images/DashboardCards_setup_4.png';
import Ellipse2Image from 'src/assets/images/DashboardCards_Ellipse_2.png';
import Ellipse3Image from 'src/assets/images/DashboardCards_Ellipse_3.png';
import Ellipse4Image from 'src/assets/images/DashboardCards_Ellipse_4.png';
import Ellipse5Image from 'src/assets/images/DashboardCards_Ellipse_5.png';
import Ellipse10Image from 'src/assets/images/DashboardCards_Ellipse_10.png';
import Ellipse6Image from 'src/assets/images/DashboardCards_Ellipse_6.png';
import Ellipse7Image from 'src/assets/images/DashboardCards_Ellipse_7.png';
import Ellipse8Image from 'src/assets/images/DashboardCards_Ellipse_8.png';
import Ellipse9Image from 'src/assets/images/DashboardCards_Ellipse_9.png';
import Polygon1Image from 'src/assets/images/DashboardCards_Polygon_1.png';
import Polygon2Image from 'src/assets/images/DashboardCards_Polygon_2.png';
import Polygon3Image from 'src/assets/images/DashboardCards_Polygon_3.png';
import Polygon4Image from 'src/assets/images/DashboardCards_Polygon_4.png';
import { styled } from '@mui/material/styles';
import { DashboardCardsProps } from 'src/types';

const DashboardCards1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `612px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Frame: any = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `520px`,
  height: `250px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
});

const MachineStatus: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `200px`,
  height: `60px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Cnc1: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `130px`,
  height: `40px`,
  position: `absolute`,
  left: `0px`,
  top: `70px`,
});

const Cnc2: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `130px`,
  height: `40px`,
  position: `absolute`,
  left: `130px`,
  top: `70px`,
});

const Cnc3: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `130px`,
  height: `40px`,
  position: `absolute`,
  left: `260px`,
  top: `70px`,
});

const Cmm1: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `130px`,
  height: `40px`,
  position: `absolute`,
  left: `390px`,
  top: `70px`,
});

const Setup1: any = styled('img')({
  height: `50px`,
  width: `49.19px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `138px`,
  top: `218px`,
});

const Rectangle3: any = styled('div')({
  backgroundColor: `rgba(243, 84, 84, 1)`,
  borderRadius: `5px`,
  width: `71px`,
  height: `15px`,
  position: `absolute`,
  left: `29px`,
  top: `132px`,
});

const Setup2: any = styled('img')({
  height: `50px`,
  width: `49.19px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `268px`,
  top: `218px`,
});

const Rectangle4: any = styled('div')({
  backgroundColor: `rgba(246, 167, 49, 1)`,
  borderRadius: `5px`,
  width: `71px`,
  height: `15px`,
  position: `absolute`,
  left: `160px`,
  top: `132px`,
});

const Setup3: any = styled('img')({
  height: `50px`,
  width: `49.19px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `399px`,
  top: `218px`,
});

const Rectangle5: any = styled('div')({
  backgroundColor: `rgba(119, 199, 56, 1)`,
  borderRadius: `5px`,
  width: `71px`,
  height: `15px`,
  position: `absolute`,
  left: `291px`,
  top: `132px`,
});

const Setup4: any = styled('img')({
  height: `50px`,
  width: `49.19px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `528px`,
  top: `218px`,
});

const Rectangle6: any = styled('div')({
  backgroundColor: `rgba(119, 199, 56, 1)`,
  borderRadius: `5px`,
  width: `71px`,
  height: `15px`,
  position: `absolute`,
  left: `420px`,
  top: `132px`,
});

const Frame28: any = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `520px`,
  height: `250px`,
  left: `571px`,
  top: `0px`,
  overflow: `hidden`,
});

const ConnectorStatus: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `200px`,
  height: `60px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Ellipse2: any = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `64px`,
  top: `70px`,
});

const CncMachine1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `120px`,
  height: `40px`,
  position: `absolute`,
  left: `109px`,
  top: `60px`,
});

const Ellipse3: any = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `64px`,
  top: `110px`,
});

const CncMachine2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `120px`,
  height: `40px`,
  position: `absolute`,
  left: `109px`,
  top: `100px`,
});

const Ellipse4: any = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `64px`,
  top: `150px`,
});

const CncMachine3: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `120px`,
  height: `40px`,
  position: `absolute`,
  left: `109px`,
  top: `140px`,
});

const Ellipse5: any = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `64px`,
  top: `190px`,
});

const Ellipse10: any = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `64px`,
  top: `190px`,
});

const Cmm11: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `120px`,
  height: `40px`,
  position: `absolute`,
  left: `109px`,
  top: `180px`,
});

const Ellipse6: any = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `290px`,
  top: `70px`,
});

const Cmm2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `116px`,
  height: `40px`,
  position: `absolute`,
  left: `339px`,
  top: `60px`,
});

const Ellipse7: any = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `290px`,
  top: `110px`,
});

const Press1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `116px`,
  height: `40px`,
  position: `absolute`,
  left: `339px`,
  top: `100px`,
});

const Ellipse8: any = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `290px`,
  top: `150px`,
});

const Press2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `116px`,
  height: `40px`,
  position: `absolute`,
  left: `339px`,
  top: `140px`,
});

const Ellipse9: any = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `290px`,
  top: `190px`,
});

const Press3: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `116px`,
  height: `40px`,
  position: `absolute`,
  left: `339px`,
  top: `180px`,
});

const Frame29: any = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `520px`,
  height: `250px`,
  left: `0px`,
  top: `300px`,
  overflow: `hidden`,
});

const Alert1: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `200px`,
  height: `60px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Cnc1Offline: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `366px`,
  height: `40px`,
  position: `absolute`,
  left: `109px`,
  top: `60px`,
});

const Polygon1: any = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `41px`,
  top: `70px`,
});

const Line3: any = styled('div')({
  border: `1px solid rgba(255, 255, 255, 1)`,
  width: `439px`,
  height: `0px`,
  position: `absolute`,
  left: `41px`,
  top: `101px`,
});

const Cnc2OnStandby: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `366px`,
  height: `40px`,
  position: `absolute`,
  left: `109px`,
  top: `101px`,
});

const Polygon2: any = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `41px`,
  top: `111px`,
});

const Line4: any = styled('div')({
  border: `1px solid rgba(255, 255, 255, 1)`,
  width: `439px`,
  height: `0px`,
  position: `absolute`,
  left: `41px`,
  top: `142px`,
});

const Cmm2ConnectorDown: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `366px`,
  height: `40px`,
  position: `absolute`,
  left: `108px`,
  top: `141px`,
});

const Polygon3: any = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `40px`,
  top: `151px`,
});

const Line5: any = styled('div')({
  border: `1px solid rgba(255, 255, 255, 1)`,
  width: `439px`,
  height: `0px`,
  position: `absolute`,
  left: `40px`,
  top: `182px`,
});

const Press1ConnectorDown: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `366px`,
  height: `40px`,
  position: `absolute`,
  left: `109px`,
  top: `181px`,
});

const Polygon4: any = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `41px`,
  top: `191px`,
});

const Line6: any = styled('div')({
  border: `1px solid rgba(255, 255, 255, 1)`,
  width: `439px`,
  height: `0px`,
  position: `absolute`,
  left: `41px`,
  top: `222px`,
});

const Frame30: any = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `520px`,
  height: `250px`,
  left: `571px`,
  top: `300px`,
  overflow: `hidden`,
});

const MachineLoading: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `200px`,
  height: `60px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Cnc11: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `130px`,
  height: `40px`,
  position: `absolute`,
  left: `0px`,
  top: `187px`,
});

const Cnc21: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `130px`,
  height: `40px`,
  position: `absolute`,
  left: `130px`,
  top: `187px`,
});

const Cnc31: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `130px`,
  height: `40px`,
  position: `absolute`,
  left: `260px`,
  top: `187px`,
});

const Cmm12: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `130px`,
  height: `40px`,
  position: `absolute`,
  left: `390px`,
  top: `187px`,
});

const Rectangle7: any = styled('div')({
  backgroundColor: `rgba(120, 115, 115, 1)`,
  borderRadius: `0px`,
  width: `39px`,
  height: `113px`,
  position: `absolute`,
  left: `47px`,
  top: `64px`,
});

const Rectangle8: any = styled('div')({
  backgroundColor: `rgba(119, 199, 56, 1)`,
  borderRadius: `0px`,
  width: `39px`,
  height: `88px`,
  position: `absolute`,
  left: `47px`,
  top: `89px`,
});

const Rectangle9: any = styled('div')({
  backgroundColor: `rgba(120, 115, 115, 1)`,
  borderRadius: `0px`,
  width: `39px`,
  height: `113px`,
  position: `absolute`,
  left: `181px`,
  top: `64px`,
});

const Rectangle10: any = styled('div')({
  backgroundColor: `rgba(243, 84, 84, 1)`,
  borderRadius: `0px`,
  width: `39px`,
  height: `16px`,
  position: `absolute`,
  left: `181px`,
  top: `161px`,
});

const Rectangle11: any = styled('div')({
  backgroundColor: `rgba(120, 115, 115, 1)`,
  borderRadius: `0px`,
  width: `39px`,
  height: `113px`,
  position: `absolute`,
  left: `307px`,
  top: `64px`,
});

const Rectangle12: any = styled('div')({
  backgroundColor: `rgba(246, 167, 49, 1)`,
  borderRadius: `0px`,
  width: `39px`,
  height: `48px`,
  position: `absolute`,
  left: `307px`,
  top: `129px`,
});

const Rectangle13: any = styled('div')({
  backgroundColor: `rgba(120, 115, 115, 1)`,
  borderRadius: `0px`,
  width: `39px`,
  height: `113px`,
  position: `absolute`,
  left: `436px`,
  top: `64px`,
});

const Rectangle14: any = styled('div')({
  backgroundColor: `rgba(119, 199, 56, 1)`,
  borderRadius: `0px`,
  width: `39px`,
  height: `99px`,
  position: `absolute`,
  left: `436px`,
  top: `78px`,
});

const Frame31: any = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `520px`,
  height: `250px`,
  left: `0px`,
  top: `600px`,
  overflow: `hidden`,
});

const NewCard: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(120, 115, 115, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `200px`,
  height: `60px`,
  position: `absolute`,
  left: `160px`,
  top: `88px`,
});

const Frame32: any = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `520px`,
  height: `250px`,
  left: `571px`,
  top: `600px`,
  overflow: `hidden`,
});

const NewCard1: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(120, 115, 115, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `200px`,
  height: `60px`,
  position: `absolute`,
  left: `160px`,
  top: `88px`,
});

function DashboardCards(props: DashboardCardsProps): JSX.Element {
  return (
    <DashboardCards1 className={props.className}>
      <Frame>
        <MachineStatus>{`Machine Status`}</MachineStatus>
        <Cnc1>{`CNC  1`}</Cnc1>
        <Cnc2>{`CNC  2`}</Cnc2>
        <Cnc3>{`CNC  3`}</Cnc3>
        <Cmm1>{`CMM 1`}</Cmm1>
        <Setup1 src={Setup1Image} loading="lazy" alt={'setup 1'} />
        <Rectangle3></Rectangle3>
        <Setup2 src={Setup2Image} loading="lazy" alt={'setup 2'} />
        <Rectangle4></Rectangle4>
        <Setup3 src={Setup3Image} loading="lazy" alt={'setup 3'} />
        <Rectangle5></Rectangle5>
        <Setup4 src={Setup4Image} loading="lazy" alt={'setup 4'} />
        <Rectangle6></Rectangle6>
      </Frame>
      <Frame28>
        <ConnectorStatus>{`Connector Status`}</ConnectorStatus>
        <Ellipse2 src={Ellipse2Image} loading="lazy" alt={'Ellipse 2'} />
        <CncMachine1>{`CNC Machine 1`}</CncMachine1>
        <Ellipse3 src={Ellipse3Image} loading="lazy" alt={'Ellipse 3'} />
        <CncMachine2>{`CNC Machine 2`}</CncMachine2>
        <Ellipse4 src={Ellipse4Image} loading="lazy" alt={'Ellipse 4'} />
        <CncMachine3>{`CNC Machine 3`}</CncMachine3>
        <Ellipse5 src={Ellipse5Image} loading="lazy" alt={'Ellipse 5'} />
        <Ellipse10 src={Ellipse10Image} loading="lazy" alt={'Ellipse 10'} />
        <Cmm11>{`CMM 1`}</Cmm11>
        <Ellipse6 src={Ellipse6Image} loading="lazy" alt={'Ellipse 6'} />
        <Cmm2>{`CMM 2`}</Cmm2>
        <Ellipse7 src={Ellipse7Image} loading="lazy" alt={'Ellipse 7'} />
        <Press1>{`Press 1`}</Press1>
        <Ellipse8 src={Ellipse8Image} loading="lazy" alt={'Ellipse 8'} />
        <Press2>{`Press 2`}</Press2>
        <Ellipse9 src={Ellipse9Image} loading="lazy" alt={'Ellipse 9'} />
        <Press3>{`Press 3`}</Press3>
      </Frame28>
      <Frame29>
        <Alert1>{`Alert`}</Alert1>
        <Cnc1Offline>{`! CNC 1 Offline !`}</Cnc1Offline>
        <Polygon1 src={Polygon1Image} loading="lazy" alt={'Polygon 1'} />
        <Line3></Line3>
        <Cnc2OnStandby>{`! CNC 2 on Standby  !`}</Cnc2OnStandby>
        <Polygon2 src={Polygon2Image} loading="lazy" alt={'Polygon 2'} />
        <Line4></Line4>
        <Cmm2ConnectorDown>{`! CMM 2 connector down  !`}</Cmm2ConnectorDown>
        <Polygon3 src={Polygon3Image} loading="lazy" alt={'Polygon 3'} />
        <Line5></Line5>
        <Press1ConnectorDown>
          {`! Press 1 connector down  !`}
        </Press1ConnectorDown>
        <Polygon4 src={Polygon4Image} loading="lazy" alt={'Polygon 4'} />
        <Line6></Line6>
      </Frame29>
      <Frame30>
        <MachineLoading>{`Machine Loading`}</MachineLoading>
        <Cnc11>{`CNC  1`}</Cnc11>
        <Cnc21>{`CNC  2`}</Cnc21>
        <Cnc31>{`CNC  3`}</Cnc31>
        <Cmm12>{`CMM 1`}</Cmm12>
        <Rectangle7></Rectangle7>
        <Rectangle8></Rectangle8>
        <Rectangle9></Rectangle9>
        <Rectangle10></Rectangle10>
        <Rectangle11></Rectangle11>
        <Rectangle12></Rectangle12>
        <Rectangle13></Rectangle13>
        <Rectangle14></Rectangle14>
      </Frame30>
      <Frame31>
        <NewCard>{`New Card`}</NewCard>
      </Frame31>
      <Frame32>
        <NewCard1>{`New Card`}</NewCard1>
      </Frame32>
    </DashboardCards1>
  );
}

export default DashboardCards;
