/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Capture1Image from 'src/assets/images/SideBar_Capture_1.png';
import MithrylWhite1Image from 'src/assets/images/SideBar_mithryl_white_1.png';
import { styled } from '@mui/material/styles';
import { SideBarProps } from 'src/types';

const SideBar1: any = styled('div')({
  backgroundColor: `rgba(35, 47, 64, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Capture1: any = styled('img')({
  height: `128px`,
  width: `147px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `39px`,
  top: `31px`,
});

const Line1: any = styled('div')({
  border: `3px solid rgba(243, 112, 73, 1)`,
  width: `163px`,
  height: `0px`,
  position: `absolute`,
  left: `32px`,
  top: `181px`,
});

const Dashboard: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `163px`,
  height: `39px`,
  position: `absolute`,
  left: `32px`,
  top: `200px`,
});

const MithrylWhite1: any = styled('img')({
  height: `37px`,
  width: `128px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `49px`,
  top: `935px`,
});

const Line2: any = styled('div')({
  border: `3px solid rgba(243, 112, 73, 1)`,
  width: `163px`,
  height: `0px`,
  position: `absolute`,
  left: `31px`,
  top: `895px`,
});

const MyFactory: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `163px`,
  height: `42px`,
  position: `absolute`,
  left: `32px`,
  top: `252px`,
});

function SideBar(props: SideBarProps): JSX.Element {
  return (
    <SideBar1 className={props.className}>
      <Capture1 src={Capture1Image} loading="lazy" alt={'Capture 1'} />
      <Line1></Line1>
      <Dashboard>{`Dashboard`}</Dashboard>
      <MithrylWhite1
        src={MithrylWhite1Image}
        loading="lazy"
        alt={'mithryl_white 1'}
      />
      <Line2></Line2>
      <MyFactory>{`My Factory`}</MyFactory>
    </SideBar1>
  );
}

export default SideBar;
