/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import MillingMachine2Image from 'src/assets/images/Dashboard_milling_machine_2.png';
import PressMachine96889431Image from 'src/assets/images/Dashboard_press_machine_9688943_1.png';
import MillingMachine1Image from 'src/assets/images/Dashboard_milling_machine_1.png';
import { styled } from '@mui/material/styles';
import { DashboardProps } from 'src/types';

const Dashboard1: any = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `685px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const AssetType: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `79px`,
  height: `105px`,
  position: `absolute`,
  left: `110px`,
  top: `0px`,
});

const MachineIdDescription: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `221px`,
  height: `49px`,
  position: `absolute`,
  left: `266px`,
  top: `31px`,
});

const ProgramNumber: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `83px`,
  height: `49px`,
  position: `absolute`,
  left: `564px`,
  top: `31px`,
});

const MachineStatus: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `131px`,
  height: `101px`,
  position: `absolute`,
  left: `718px`,
  top: `2px`,
});

const DataCapture: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `81px`,
  height: `77px`,
  position: `absolute`,
  left: `912px`,
  top: `14px`,
});

const Rectangle1: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `3px`,
  width: `15px`,
  height: `15px`,
  position: `absolute`,
  left: `47px`,
  top: `48px`,
});

const MachineData: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1048px`,
  height: `550px`,
  left: `18px`,
  top: `118px`,
  overflow: `hidden`,
});

const Line4: any = styled('div')({
  border: `1px solid rgba(157, 157, 157, 1)`,
  width: `1000px`,
  height: `0px`,
  position: `absolute`,
  left: `20px`,
  top: `100px`,
});

const MillingMachine2: any = styled('img')({
  height: `50px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `107px`,
  top: `136px`,
});

const PressMachine96889431: any = styled('img')({
  height: `50px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `107px`,
  top: `249px`,
});

const Cnc1HermleC52UMtSpan1: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Cnc1HermleC52UMtSpan2: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Cnc1HermleC52UMt: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `251px`,
  height: `49px`,
  position: `absolute`,
  left: `224px`,
  top: `28px`,
});

const Q659711: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `83px`,
  height: `49px`,
  position: `absolute`,
  left: `546px`,
  top: `28px`,
});

const Automated: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `115px`,
  height: `77px`,
  position: `absolute`,
  left: `875px`,
  top: `11px`,
});

const Automated1: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `115px`,
  height: `77px`,
  position: `absolute`,
  left: `875px`,
  top: `123px`,
});

const Automated2: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `115px`,
  height: `77px`,
  position: `absolute`,
  left: `875px`,
  top: `230px`,
});

const Cnc2DoosanPuma2600Span1: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Cnc2DoosanPuma2600Span2: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Cnc2DoosanPuma2600: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `251px`,
  height: `49px`,
  position: `absolute`,
  left: `224px`,
  top: `143px`,
});

const Q659851: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `83px`,
  height: `49px`,
  position: `absolute`,
  left: `546px`,
  top: `143px`,
});

const Q021105: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(234, 142, 115, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `131px`,
  height: `101px`,
  position: `absolute`,
  left: `700px`,
  top: `114px`,
});

const Press1Wickert5000PsSpan1: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Press1Wickert5000PsSpan2: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Press1Wickert5000Ps: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `251px`,
  height: `49px`,
  position: `absolute`,
  left: `224px`,
  top: `246px`,
});

const Q659961: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `83px`,
  height: `49px`,
  position: `absolute`,
  left: `546px`,
  top: `246px`,
});

const Q000000: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `131px`,
  height: `101px`,
  position: `absolute`,
  left: `700px`,
  top: `217px`,
});

const Rectangle3: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `3px`,
  width: `15px`,
  height: `15px`,
  position: `absolute`,
  left: `29px`,
  top: `42px`,
});

const Rectangle4: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `3px`,
  width: `15px`,
  height: `15px`,
  position: `absolute`,
  left: `29px`,
  top: `154px`,
});

const Rectangle5: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `3px`,
  width: `15px`,
  height: `15px`,
  position: `absolute`,
  left: `29px`,
  top: `266px`,
});

const MillingMachine1: any = styled('img')({
  height: `50px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `107px`,
  top: `24px`,
});

const Line3: any = styled('div')({
  border: `1px solid rgba(157, 157, 157, 1)`,
  width: `1000px`,
  height: `0px`,
  position: `absolute`,
  left: `20px`,
  top: `215px`,
});

const Q040333: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(28, 155, 7, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `131px`,
  height: `101px`,
  position: `absolute`,
  left: `700px`,
  top: `-1px`,
});

function Dashboard(props: DashboardProps): JSX.Element {
  return (
    <Dashboard1 className={props.className}>
      <AssetType>{`Asset Type`}</AssetType>
      <MachineIdDescription>{`Machine ID & Description`}</MachineIdDescription>
      <ProgramNumber>{`Program Number`}</ProgramNumber>
      <MachineStatus>{`Machine Status`}</MachineStatus>
      <DataCapture>{`Data Capture`}</DataCapture>
      <Rectangle1></Rectangle1>
      <MachineData>
        <Line4></Line4>
        <MillingMachine2
          src={MillingMachine2Image}
          loading="lazy"
          alt={'milling-machine 2'}
        />
        <PressMachine96889431
          src={PressMachine96889431Image}
          loading="lazy"
          alt={'press-machine_9688943 1'}
        />
        <Cnc1HermleC52UMt>
          <Cnc1HermleC52UMtSpan1>{`CNC 1`}</Cnc1HermleC52UMtSpan1>
          <Cnc1HermleC52UMtSpan2>{`: Hermle C52 U MT`}</Cnc1HermleC52UMtSpan2>
        </Cnc1HermleC52UMt>
        <Q659711>{`65971/1`}</Q659711>
        <Automated>{`Automated`}</Automated>
        <Automated1>{`Automated`}</Automated1>
        <Automated2>{`Automated`}</Automated2>
        <Cnc2DoosanPuma2600>
          <Cnc2DoosanPuma2600Span1>{`CNC 2`}</Cnc2DoosanPuma2600Span1>
          <Cnc2DoosanPuma2600Span2>{`: Doosan PUMA 2600`}</Cnc2DoosanPuma2600Span2>
        </Cnc2DoosanPuma2600>
        <Q659851>{`65985/1`}</Q659851>
        <Q021105>{`02 : 11 : 05`}</Q021105>
        <Press1Wickert5000Ps>
          <Press1Wickert5000PsSpan1>{`PRESS 1`}</Press1Wickert5000PsSpan1>
          <Press1Wickert5000PsSpan2>{`: WICKERT 5000PS`}</Press1Wickert5000PsSpan2>
        </Press1Wickert5000Ps>
        <Q659961>{`65996/1`}</Q659961>
        <Q000000>{`00 : 00 : 00`}</Q000000>
        <Rectangle3></Rectangle3>
        <Rectangle4></Rectangle4>
        <Rectangle5></Rectangle5>
        <MillingMachine1
          src={MillingMachine1Image}
          loading="lazy"
          alt={'milling-machine 1'}
        />
        <Line3></Line3>
        <Q040333>{`04 : 03 : 33`}</Q040333>
      </MachineData>
    </Dashboard1>
  );
}

export default Dashboard;
