/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import SideBarLogin from 'src/components/SideBarLogin/SideBarLogin';
import Authentication1 from 'src/components/Authentication1/Authentication1';
import { LoginProps } from 'src/types';

const Login1: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const SideBarLogin1: any = styled(SideBarLogin)(({ theme }: any) => ({
  width: `125px`,
  height: `1024px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Authentication11: any = styled(Authentication1)(({ theme }: any) => ({
  width: `622px`,
  height: `733px`,
  position: `absolute`,
  left: `428px`,
  top: `193px`,
}));

function Login(props: LoginProps): JSX.Element {
  return (
    <Login1 className={props.className}>
      <SideBarLogin1 />
      <Authentication11 />
    </Login1>
  );
}

export default Login;
