/**********************************************************************
 *
 *   Types file generated by Quest
 *
 *   Types for the components props go in this file
 *   To set up custom types for the components props, edit the corresponding types in this file
 *   Once you edit a type to no longer by "any", be careful to not override it on your next export
 *   Verify diff before merging
 *
 *   For help and further details refer to:
 *   https://docs.quest.ai/react/fundamentals/exporting-code
 *
 *
 **********************************************************************/

export interface DashboardProps {
  className?: any;
}

export interface SampleCardProps {
  className?: any;
  metadata: any;
}

export interface SampleCardGridProps {
  className?: any;
}

export interface LayoutProductPage1Props {
  className?: any;
}

export interface ProductPage1Props {
  className?: any;
}

export interface ShopNavbar1Props {
  className?: any;
}

export interface ShoppingFooter1Props {
  className?: any;
}

export interface Recomend1Props {
  className?: any;
}

export interface Recommend1Props {
  className?: any;
}

export interface ShopBtn1Props {
  className?: any;
}

export interface RuntimeEx1Props {
  className?: any;
  prop1: any;
}

export interface DemoCardProps {
  className?: any;
  metadata: any;
}

export interface Desktop1Props {
  className?: any;
}

export interface SideBarProps {
  className?: any;
}

export interface SearchBarProps {
  className?: any;
}

export interface ExportProps {
  className?: any;
}

export interface UserControlSettingsProps {
  className?: any;
}

export interface LoginProps {
  className?: any;
}

export interface SideBarLoginProps {
  className?: any;
}

export interface Login1Props {
  className?: any;
}

export interface Dashboard1Props {
  className?: any;
}

export interface DashboardCardsProps {
  className?: any;
}

export interface DashboardMainProps {
  className?: any;
};
