/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import SideBarImage from 'src/assets/images/DashboardMain_Side_Bar.png';
import ExportImage from 'src/assets/images/DashboardMain_Export.png';
import UserControlSettingsImage from 'src/assets/images/DashboardMain_User_Control___Settings.png';
import DashboardImage from 'src/assets/images/DashboardMain_Dashboard.png';
import SearchImage from 'src/assets/images/DashboardMain____Search.png';
import { styled } from '@mui/material/styles';
import { DashboardMainProps } from 'src/types';

const DashboardMain1: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const SideBar: any = styled('img')({
  height: `1024px`,
  width: `225px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Export: any = styled('img')({
  height: `45px`,
  width: `280px`,
  position: `absolute`,
  left: `280px`,
  top: `888px`,
});

const UserControlSettings: any = styled('img')({
  height: `45px`,
  width: `99px`,
  position: `absolute`,
  left: `1260px`,
  top: `30px`,
});

const Overview: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `280px`,
  top: `135px`,
});

const Frame9: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1091px`,
  left: `280px`,
  top: `200px`,
  overflow: `hidden`,
});

const AssetType: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `79px`,
  height: `105px`,
  margin: `0px`,
});

const MachineIdDescription: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `221px`,
  height: `49px`,
  margin: `0px 0px 0px 65px`,
});

const ProgramNumber: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `83px`,
  height: `49px`,
  margin: `0px 0px 0px 65px`,
});

const MachineStatus: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `131px`,
  height: `101px`,
  margin: `0px 0px 0px 65px`,
});

const DataCapture: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `81px`,
  height: `77px`,
  margin: `0px 0px 0px 65px`,
});

const Dashboard: any = styled('img')({
  height: `550px`,
  width: `1091px`,
  position: `absolute`,
  left: `280px`,
  top: `305px`,
});

const Search: any = styled('img')({
  height: `48px`,
  width: `896px`,
  position: `absolute`,
  left: `280px`,
  top: `30px`,
});

function DashboardMain(props: DashboardMainProps): JSX.Element {
  return (
    <DashboardMain1 className={props.className}>
      <SideBar src={SideBarImage} loading="lazy" alt={'Side Bar'} />
      <Export src={ExportImage} loading="lazy" alt={'Export'} />
      <UserControlSettings
        src={UserControlSettingsImage}
        loading="lazy"
        alt={'User Control & Settings'}
      />
      <Overview>{`Overview`}</Overview>
      <Frame9>
        <AssetType>{`Asset Type`}</AssetType>
        <MachineIdDescription>
          {`Machine ID & Description`}
        </MachineIdDescription>
        <ProgramNumber>{`Program Number`}</ProgramNumber>
        <MachineStatus>{`Machine Status`}</MachineStatus>
        <DataCapture>{`Data Capture`}</DataCapture>
      </Frame9>
      <Dashboard src={DashboardImage} loading="lazy" alt={'Dashboard'} />
      <Search src={SearchImage} loading="lazy" alt={'& Search'} />
    </DashboardMain1>
  );
}

export default DashboardMain;
